# Generated by Django 6.0.3 on 2026-03-30 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('hospital', 'Hospital'), ('juice_shop', 'Juice Shop'), ('voting_booth', 'Voting Booth'), ('bank', 'Bank'), ('clinic', 'Clinic'), ('other', 'Other Service')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('estimated_service_time', models.IntegerField(default=5, help_text='Time in minutes per token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_queues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Queue Services',
            },
        ),
    ]
